### ISSUE TITLE
Need to indicate that libxml2 support is required

### ISSUE THREAD

**Issue by ghost** [asavonic/outlook.el#1]
Trying to use this with the emacs version distributed with Fedora 23 (yes I know it is getting old at this point) is a no go, due to the lack of libxml2 support. I am going to compile emacs on my machine to see if that fixes it.

```C-h v system-configuration-options RET``` gives:
```system-configuration-options is a variable defined in `C source code'.
Its value is
"--build=i686-redhat-linux-gnu --host=i686-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no build_alias=i686-redhat-linux-gnu host_alias=i686-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables' LDFLAGS=-Wl,-z,relro"```

**Comment by asavonic** [comment]
Hi @niebieskitrociny,
Thanks for the feedback. Indeed, the package requires Emacs to be compiled with libxml2 and now I added this information to the README.
